### ISSUE TITLE
Error: dyld: Library not loaded: libboost_thread.dylib

### ISSUE THREAD

**Issue by CNuge** [tongchf/mvqtlcim#1]
Hello,

I've downloaded the program and unzipped the mvqtlcim executable on mac OS.
I however encounter a problem getting the example working.

When running the example command: `./mvqtlcim -i example.txt -b 5 -m 1`
Produces the following output:
```
dyld: Library not loaded: libboost_thread.dylib
  Referenced from: /Users/Cam/Desktop/mvqtlcim-master/./mvqtlcim
  Reason: image not found
Abort trap: 6
```
I believe the executable has certain dependencies that are not included? Or is there supporting software/C++ libraries that a user needs to have installed?

Thanks, if you could provide some information on what is required for a proper setup it would be greatly appreciated. I would be very interested in using this program for a qtl analysis on an outbred population.

- Cam

**Comment by hulizhong** [comment]
can u set $dyld_library_path ??
